language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: L1x9Ww6ruI5tfMng1X4i6WpUHmMqLQZXZw5fbb5FagyUqutEBU1y6/JgvMytizGiJuQgxo+PLqyzoOcY57GM2lTx9UZZJkz9PlxS+KG55zXgseZvNKT4GAOO3aq0pq6a92wNEQtM71F678nw1UAatzbcMT+dKjpt4a8EnQA0ZXUR7dbwovJO3u2k4N21ffl1t6cL8nTTddLZ9Hr/VVBfF6TAx/2XbdqXVZAM2lbcWfpjMofpPgf4+VzZ4Lv7gKbwQ1S9j+aeSDwhvYkRjWQTPqvQL0mfhiIxDhS7PIrsvlxcUCgz6zc8qpTjGkEXnkJCftDvGVDr6flyvptl1JcVdADIZ9D4JGfT2xDkg7156uZLtdQd4sVFCyCtP5TLZLvhOyF7+ORccVyTkBtSbQi1sefdsJRqGYLrZnUk3QkVQM2glb42dqrqGeuXIYeKtesxzLr7goVVtqFUcU0yrb531eR/9FPgap82gWg6/RuqCHlrO0c1rn6StaVQfLLCIfTFFe/zlHZUaEz4uRH2dWgz040VOqjnvmep+2jOMNPLZ5NLQcDHYTi6fFdnhqIDivaobJZwLlIdRYNpys+S5jMTPGhgYQDnArf9IX8W1U6MBwVa+kB4GPZOPA3lVAGEbhWRHEUNPv+tsd7IXsDnpDYxPF+ZO8Gdm9ucKv7Nzz77cps=
