language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: uyCMT4qb21j0RGBh+LT3bLWF8uVAC2A63BMZIGWJKnGmH4tZDTg/d4DtxLoIHuGaYxlla9g4W4unF0ehUeFAtrw53D4WED3O9ZSIneokCJkEN0pRZFxEncuYolUky61zuKOcW9Mx1dmxIHbAmIkqgstnUGxQNqKf2vbWTyvI4WCmUqvGwGk9Sw1HLyMfaIDhJP7XcGCUKc3qd0YP9Wa5BqNZl4VBL8dcL/vPpl/wjCl4X8IMl7hBkR8rtdQlgLdAG3B0kVDHn7rZgt7uZUFFUIW9bogeZxkO4ggOegCCLdFXHzGqTe7b+GM0//LTCjwWDNBPB2PCBWDgaXF66Ysi9l48v4sY220HLkjlasVKZzatSL58eAiio4oVL73t3y1ve2RUWuHIlwdoRrVWm5nfEqK/khaK0bpTZ+O9GlhfGxkq1dd0jN14IeEnYLs8tuNJZEMUlbRj+HdV9hlkhhrHQI2n7HOH/U9c1R0MNZMRzXTpQdct4rxV39yCVrq7pqigjnnZ2vMFrkLZs7irTrkUB+bOCSSkHc0HMvxKy+ZiZ88wuOsIcGWOhKdHShugbCY0QmPiZ7BBg4BFP2pw70v8GTgSQQ24rWe3rB0DsScHWOLna/W/F9bJCDNrbzdkLSIxw5MhYI4Iauis9+mI3Yhe6dvkw1XMoKiWGZf63x90/e4=
  app: marmalade-crawler
  on:
    repo: Jlabroy/marmalade-crawler
